add build log

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -1,4 +1,4 @@
-name: Deploy to GitHub Pages
+name: 部署到GitHubPages
 
 on:
   # 每次推送到 `main` 分支时触发这个“工作流程”
@@ -17,16 +17,18 @@ jobs:
   build:
     runs-on: ubuntu-latest
     steps:
-      - name: Checkout your repository using git
+      - name:  使用git检出代码
         uses: actions/checkout@v4
       - name: Install, build, and upload your site
         uses: withastro/action@v3
-      - name: Print Directory Structure (Simple)
+      - name: 打印目录结构
         run: |
           echo "=== Root Directory ==="
           ls -la
           echo "=== Dist Folder (if exists) ==="
           ls -la dist/ || echo "Dist folder not found"
+          echo "=== Root Folder Pubic (if exists) ==="
+          ls -la public/ || echo "Public folder not found"
         # with:
           # path: . # 存储库中 Astro 项目的根位置。（可选）
           # node-version: 20 # 用于构建站点的特定 Node.js 版本，默认为 20。（可选）
